### ISSUE TITLE
Disabling specific chickens?

### ISSUE THREAD

**Issue by bobhenl** [kii-chan-reloaded/GeneticChickengineering#9]
```
GCE_NETHERITE_CHICKEN:
  enabled: false
  can-be-used-in-workbenches: false
  hide-in-guide: false
  allow-enchanting: true
  allow-disenchanting: true

GCE_NETHERITE_CHICKEN_ICON:
  enabled: false
  can-be-used-in-workbenches: false
  hide-in-guide: false
  allow-enchanting: true
  allow-disenchanting: true
```

Hi, how can we disable specific chickens? This didn't work.
